# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-09 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_businesses_privileges_userprofiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesses',
            options={'permissions': (('view_task', 'Can see available tasks'), ('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed'))},
        ),
    ]
