# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-17 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170809_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesses',
            options={'permissions': (('can_restart_node', 'can_restart_node'), ('can_stop_node', 'can_stop_node'))},
        ),
    ]
