# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-21 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170817_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesses',
            options={'permissions': (('can_restart_node', 'can_restart_node'), ('can_stop_node', 'can_stop_node'), ('can_start_node', 'can_start_node'), ('can_execute_cmd', 'can_execute_cmd'), ('can_upload_file', 'can_upload_file'), ('can_change_appstatus', 'can_change_appstatus'), ('can_manage_user', 'can_manage_user'), ('can_manage_business', 'can_manage_business'), ('can_manage_privi', 'can_manage_privi'), ('can_manage_asset', 'can_manage_asset'))},
        ),
    ]
