# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-15 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASSETINFO',
            fields=[
                ('AST_NUM', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SR_NUM', models.CharField(max_length=20, unique=True)),
                ('DEV_NAME', models.CharField(max_length=20)),
                ('DEV_ALS', models.CharField(max_length=20)),
                ('DEV_TYP', models.CharField(max_length=20)),
                ('DEV_MOD', models.CharField(max_length=20)),
                ('OS_TYP', models.CharField(max_length=20, null=True)),
                ('ADMIN', models.CharField(max_length=20)),
                ('OWN_DPT', models.CharField(max_length=20)),
                ('MAN_STE', models.CharField(max_length=20)),
                ('MAN_BGN', models.CharField(max_length=20)),
                ('MAN_END', models.CharField(max_length=20)),
                ('UP_TME', models.CharField(max_length=20, null=True)),
                ('AST_LAB', models.CharField(max_length=20, unique=True)),
                ('BUS_DES', models.CharField(max_length=20, null=True)),
                ('Location', models.CharField(max_length=20)),
                ('Area', models.CharField(max_length=20)),
                ('CAB_LCA', models.CharField(max_length=20)),
                ('DEV_BGN', models.CharField(max_length=4)),
                ('DEV_END', models.CharField(max_length=4)),
                ('DEV_IP', models.CharField(max_length=15)),
                ('REMARK', models.CharField(max_length=120)),
            ],
        ),
    ]
