#/usr/bin/env python
#coding:utf-8
"""
Django settings for UAT project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import django
import djcelery
import time
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q@!8_wt=hw9l%9m!g)9a9-711cj&xhc8xp!p=byl76y4j&ce$r'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SALT_API_URL=""
SALT_API_USER=""
SALT_API_PASSWD=""

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'controller',
    'monitor',
    'django.contrib.sites',
    'backend',
    'execute',
    'djcelery',
    'filemanage',
    'hiasset',
    'jobs',
    'deploy',
    'myauth'
]
SITE_ID=1
FILE_BASE_DIR="/Users/timxie-mac/Downloads"
AUTHENTICATION_BACKENDS=(

"myauth.auth.MyCustomBackend",
"django.contrib.auth.backends.ModelBackend",
)

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
  #  'django.middleware.csrf.CsrfResponseMiddleware',
	'django.middleware.locale.LocaleMiddleware',
]


LOGIN_URL="/login"

ROOT_URLCONF = 'autoops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR+'/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'autoops.wsgi.application'


# Database

# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    #uat
  'default':{
	'ENGINE': 'django.db.backends.oracle',
       'NAME': 'uatrac1',
       'HOST':'172.16.49.200',
        'USER':'monitor',
        'PASSWORD':'Mon#2016',
        'PORT':'1521'
      # 'NAME': 'uatrac1',
       # 'HOST':'211.138.236.210',
        #'USER':'monitor',
        ##'PASSWORD':'Mon#2016',
        #'PORT':'41521',

         }       
    }


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True



USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'collect/').replace('\\', '/')
print BASE_DIR

STATICFILES_DIRS = (
  BASE_DIR+'/static',
)

oracle_conn={
    
    #uat
        'ENGINE': 'django.db.backends.oracle',
       'NAME': 'uatsrv1',
        'HOST':'172.16.49.200',
        'USER':'monitor',
        'PASSWD':'Mon#2016',
        'PORT':'1521',
        
    #downtown 
     #   """
     #'name': 'uatrac1',
     #   'host':'211.138.236.210',
     #   'user':'monitor',
     # 'passwd':'Mon#2016',
     #  'port':'41521'
    #   """

    }

BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND='redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT=['application/json']
CELERY_TASK_SERIALIZER='json'
CELERY_RESULT_SERIALIZER='json'
CELERY_TIMEZONE='Asia/Shanghai' 