# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-24 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(blank=True, null=True)),
                ('command_tag', models.IntegerField(blank=True, null=True)),
                ('execute_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salt_command_history',
            },
        ),
        migrations.CreateModel(
            name='Modindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.TextField(blank=True, null=True)),
                ('module_fun', models.TextField(blank=True, null=True)),
                ('module_des', models.TextField(blank=True, null=True)),
                ('module_exa', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salt_modindex',
            },
        ),
    ]
